site_name: –ò–Ω—Ñ–æ—Ä–º–∞—Ü–∏–æ–Ω–Ω—ã–π –ø–æ—Ä—Ç–∞–ª LS:MP
site_url: http://127.0.0.1:8000

theme:
  language: ru
  name: material

  features:
    - navigation.instant
    - navigation.instant.progress
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.expand
    - navigation.sections

  font:
    text: Inter
    code: IBM Plex Mono

  logo: assets/logo.png
  favicon: assets/favicon.ico

  palette:
    - scheme: slate
      toggle:
        icon: material/moon-waning-crescent
        name: –¢—ë–º–Ω–∞—è —Ç–µ–º–∞
      primary: deep purple
      accent: green

    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: –°–≤–µ—Ç–ª–∞—è —Ç–µ–º–∞
      primary: deep purple
      accent: green

nav:
  - ‚ÑπÔ∏è –û—Å–Ω–æ–≤–Ω–∞—è –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—è:
      - –ì–ª–∞–≤–Ω–∞—è: index.md
      - üîÆ –ö–∞–∫ –∑–∞–π—Ç–∏?:
          - –û—Å–Ω–æ–≤–Ω–∞—è –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—è: join-guide.md
          - –†–µ–∫–æ–º–µ–Ω–¥—É–µ–º—ã–µ –º–æ–¥—ã: base-mods.md
      - üåü –ú–µ—Ö–∞–Ω–∏–∫–∏ —Å–µ—Ä–≤–µ—Ä–∞:
          - –î–æ—Å—Ç—É–ø–Ω—ã–µ –∫—Ä–∞—Ñ—Ç—ã: crafts.md
          - –û–Ω–ª–∞–π–Ω –∫–∞—Ä—Ç–∞: online-map.md
          - –ü—Ä–∏–≤–∞—Ç–Ω—ã–µ —Ç–µ—Ä—Ä–∏—Ç–æ—Ä–∏–∏: private-areas.md
          - –ü–æ–¥–ø–∏—Å–∫–∞ PRIME: PRIME.md
          - –õ—É–ø–∞: magnifying_glass.md

  - üìñ –ü—Ä–∞–≤–∏–ª–∞:
      - –û—Å–Ω–æ–≤–Ω—ã–µ –ø—Ä–∞–≤–∏–ª–∞: rules/index.md
      - –ó–∞–ø—Ä–µ—â—ë–Ω–Ω—ã–µ –º–æ–¥—ã: rules/prohibited-mods.md
      - –°–∫—Ä—ã—Ç–∏–µ –∏–≥—Ä–æ–∫–æ–≤ –∏ –ø–µ—â–µ—Ä: rules/hide-players-and-caves.md

  - ‚öñÔ∏è –ó–∞–∫–æ–Ω—ã:
      - –û –≤—ã–±–æ—Ä–∞—Ö: rules/about-voiting.md

  - üõ†Ô∏è –ò—Å–ø—Ä–∞–≤–ª–µ–Ω–∏–µ –ø—Ä–æ–±–ª–µ–º:
      - –†–µ—à–µ–Ω–∏–µ –ø—Ä–æ–±–ª–µ–º: problems/index.md

  - üìú –Æ—Ä–∏–¥–∏—á–µ—Å–∫–∞—è –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—è:
      - –ü–æ–ª–∏—Ç–∏–∫–∞ –∫–æ–Ω—Ñ–∏–¥–µ–Ω—Ü–∏–∞–ª—å–Ω–æ—Å—Ç–∏: policy/privacy-policy.md
      - –ü–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—å—Å–∫–æ–µ —Å–æ–≥–ª–∞—à–µ–Ω–∏–µ: policy/eula.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - md_in_html
  - pymdownx.blocks.caption
